// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Keeper struct {
	ID           string   `json:"id"`
	Name         string   `json:"name"`
	Vaults       []*Vault `json:"vaults"`
	TotalBalance float64  `json:"totalBalance"`
}

type Mutation struct {
}

type Query struct {
}

type Transfer struct {
	ID                 string    `json:"id"`
	SourceVaultID      string    `json:"sourceVaultID"`
	DestinationVaultID string    `json:"destinationVaultID"`
	Amount             float64   `json:"amount"`
	CreatedAt          time.Time `json:"createdAt"`
}

type Vault struct {
	ID        string    `json:"id"`
	KeeperID  string    `json:"keeperID"`
	Balance   float64   `json:"balance"`
	CreatedAt time.Time `json:"createdAt"`
}
