package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.45

import (
	"context"
	"fmt"

	"github.com/yourusername/erebor-vault/graph/model"
)

// CreateVault is the resolver for the createVault field.
func (r *mutationResolver) CreateVault(ctx context.Context, keeperID string, initialDeposit float64) (*model.Vault, error) {
	panic(fmt.Errorf("not implemented: CreateVault - createVault"))
}

// TransferGold is the resolver for the transferGold field.
func (r *mutationResolver) TransferGold(ctx context.Context, sourceVaultID string, destinationVaultID string, amount float64) (*model.Transfer, error) {
	panic(fmt.Errorf("not implemented: TransferGold - transferGold"))
}

// Keepers is the resolver for the keepers field.
func (r *queryResolver) Keepers(ctx context.Context) ([]*model.Keeper, error) {
	panic(fmt.Errorf("not implemented: Keepers - keepers"))
}

// Keeper is the resolver for the keeper field.
func (r *queryResolver) Keeper(ctx context.Context, id string) (*model.Keeper, error) {
	panic(fmt.Errorf("not implemented: Keeper - keeper"))
}

// Vault is the resolver for the vault field.
func (r *queryResolver) Vault(ctx context.Context, id string) (*model.Vault, error) {
	panic(fmt.Errorf("not implemented: Vault - vault"))
}

// VaultHistory is the resolver for the vaultHistory field.
func (r *queryResolver) VaultHistory(ctx context.Context, vaultID string) ([]*model.Transfer, error) {
	panic(fmt.Errorf("not implemented: VaultHistory - vaultHistory"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
