<script lang="ts">
import {setContextClient} from "@urql/svelte";import {client} from "./lib/graphql/client";import KeeperList from "./lib/components/KeeperList.svelte";import KeeperDashboard from "./lib/components/KeeperDashboard.svelte";import CreateVaultForm from "./lib/components/CreateVaultForm.svelte";import TransferForm from "./lib/components/TransferForm.svelte";
setContextClient(client);let selectedKeeperId:string|null=$state(null);let showCreateVault=$state(false);let showTransfer=$state(false);
</script>
<main class="min-h-screen bg-gradient-to-br from-erebor-dark via-erebor-stone to-erebor-dark">
<div class="container mx-auto px-4 py-8"><header class="text-center mb-12"><h1 class="text-5xl font-bold text-erebor-gold mb-2">🏔️ Erebor Vault</h1><p class="text-erebor-light text-lg">Treasure Management</p></header>
{#if !selectedKeeperId}<div class="mb-8 flex justify-end gap-4"><button onclick={()=>showCreateVault=true} class="bg-erebor-gold text-erebor-dark px-6 py-2 rounded-lg font-semibold hover:bg-yellow-500">➕ Create Vault</button><button onclick={()=>showTransfer=true} class="bg-blue-600 text-white px-6 py-2 rounded-lg font-semibold hover:bg-blue-700">💰 Transfer</button></div><KeeperList onSelectKeeper={(id)=>selectedKeeperId=id}/>{:else}<button onclick={()=>selectedKeeperId=null} class="mb-6 bg-gray-700 text-white px-4 py-2 rounded-lg">← Back</button><KeeperDashboard keeperId={selectedKeeperId}/>{/if}
{#if showCreateVault}<div class="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center p-4 z-50"><div class="bg-white rounded-lg p-6 max-w-md w-full"><div class="flex justify-between mb-4"><h2 class="text-2xl font-bold">Create Vault</h2><button onclick={()=>showCreateVault=false} class="text-gray-500">✕</button></div><CreateVaultForm onSuccess={()=>showCreateVault=false}/></div></div>{/if}
{#if showTransfer}<div class="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center p-4 z-50"><div class="bg-white rounded-lg p-6 max-w-md w-full"><div class="flex justify-between mb-4"><h2 class="text-2xl font-bold">Transfer</h2><button onclick={()=>showTransfer=false} class="text-gray-500">✕</button></div><TransferForm onSuccess={()=>showTransfer=false}/></div></div>{/if}
</div></main>
